### ISSUE TITLE
公司项目信息在github开源真的好么......

### ISSUE THREAD

**Issue by iusearch** [ToryCrox/MimikkoManifest#1]

**Comment by ToryCrox** [comment]
只是来暂存，之后准备删掉放到公司的gitlib上。而且这些都是需要密码的。话说你是哪位？

2018-06-20 20:26 GMT+08:00 Hork <notifications@github.com>:

**Comment by iusearch** [comment]
路过而已，搜mimikko找到的

**Comment by ToryCrox** [comment]
好吧，吓我一跳。前几天才放上去就被找到了，还以为是公司的某人。。。
